# Generated by Django 4.0.1 on 2022-04-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Wav filename', max_length=200)),
                ('filesize', models.IntegerField(verbose_name='wav_filesize')),
                ('transcript', models.TextField(verbose_name='transcript')),
            ],
            options={
                'ordering': ['name', 'transcript'],
            },
        ),
    ]
