# Generated by Django 4.0.1 on 2022-03-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audios',
            new_name='Audio',
        ),
    ]
