# Generated by Django 4.0.1 on 2022-03-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textos', '0002_rename_audios_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['name', 'transcript']},
        ),
    ]
