# Generated by Django 4.0.1 on 2022-04-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Contact of whatsapp', verbose_name='contact')),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Group of whatsapp', verbose_name='group')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_message', models.DateTimeField(help_text='WhatsApp datetime')),
                ('message', models.CharField(help_text='whatsapp message', max_length=1024)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.contact')),
                ('whatsappgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.whatsappgroup')),
            ],
            options={
                'db_table': 'WhatsApp',
                'ordering': ['dt_message'],
            },
        ),
    ]
